export const userDocs = {
    userName: document.getElementById("user-name"),
    userRealname: document.getElementById("user-realname"),
    userAge: document.getElementById("user-age"),
    userSince: document.getElementById("user-since"),
    inputPass: document.querySelector("#input-pass"),
    inputField: document.querySelector("#input-field"),
    checkPassBtn: document.querySelector("#checkpass-user")
};
export const pageDocs = {
     userPBtn: document.getElementById("nav-btn-userP"),
     cardContain: document.getElementById("Card-Contain"),
     headingTop: document.getElementById("Heading-top"),
     cardShowBtn: document.getElementById("show-Cards"),
};


export const user = {
    per: {
        brukernavn: "perthedestroyer",
        navn: "Per Harald",
        alder: 20,
        brukerSiden: "20.02.2020",
        password: "meow123",
        pfp: "../images/userPfp/p-pfp.webp",
        posts: [4, 10, 15, 20, 25, 30],
    },
    emilie: {
        brukernavn: "Flowerpower",
        navn: "Emilie Solheim",
        alder: 18,
        brukerSiden: "17.04.2022",
        password: "playwell",
        pfp: "../images/userPfp/e-pfp.png",
        posts: [3, 9, 14, 19, 24, 29],
    },
    anna: {
        brukernavn: "AnnaBanana",
        navn:   "Anna Svensson",
        alder:  25,
        brukerSiden: "12.10.2019",
        password: "banana123",
        pfp: "../images/userPfp/a-pfp.png",
        posts: [1, 7, 13, 18, 23, 28],
    },
    johan: {
        brukernavn: "JohanLion",
        navn: "Johan Eriksson",
        alder: 22,
        brukerSiden: "05.06.2021",
        password: "lionking",
        pfp: "../images/userPfp/j-pfp.png",
        posts: [2, 8, 12, 17, 22, 27],
    },
    maria: {
        brukernavn: "MarialovesCats",
        navn: "Maria Rodriguez",
        alder: 30,
        brukerSiden: "03.12.2018",
        password: "catlover",
        pfp: "../images/userPfp/m-pfp.jpg",
        posts: [5, 11, 16, 21, 26, 30],
    }
};
export const infoP = [
    "Nettopp fullført en fantastisk tur i fjellene! Utsikten var pustetaking.",
    "Prøver ut en ny oppskrift i kveld. Fingrene krysset for at det blir deilig!",
    "Gleder meg til å dykke ned i en ny bok jeg plukket opp på bokhandelen. #lesetid",
    "Besøkte en fascinerende kunstutstilling i dag. Så mye kreativitet på ett sted!",
    "Nettopp fullført en fantastisk tur i fjellene! Utsikten var pustetaking.",
    "Prøver ut en ny oppskrift i kveld. Fingrene krysset for at det blir deilig!",
    "Gleder meg til å dykke ned i en ny bok jeg plukket opp på bokhandelen. #lesetid",
    "Besøkte en fascinerende kunstutstilling i dag. Så mye kreativitet på ett sted!",
    "Klar for å utforske nye steder denne helgen. Eventyr venter!",
    "Nå er det på tide å slappe av og nyte en kopp varm te. #avslapning",
    "Drømmer om å reise til fjerne land og oppleve nye kulturer. #reiselyst",
    "Inspirert til å male etter å ha sett en vakker solnedgang. #kreativitet",
    "Hjemme alene og ser på favorittfilmen min. Perfekt avslutning på dagen!",
    "Planlegger en piknik i parken med venner i helgen. #sosialt",
    "Lurer på hva fremtiden vil bringe. Uendelige muligheter!",
    "Tenker på gamle minner og smilende til de gode tidene. #nostalgi",
    "Oppdaget en ny favorittsang i dag. Musikk er virkelig magisk!",
    "Ingenting som en god bok og en kopp kaffe på en regnfull dag. #koselig",
    "Ser tilbake på året som har gått med takknemlighet. Så mye å være glad for!",
    "Drømmer om å lære seg et nytt språk. #språklæring",
    "Fascinert av stjernene på en klar natt. Universet er så mystisk!",
    "Gjør små endringer for å leve mer bærekraftig. #miljøvennlig",
    "Delte noen latter med venner i dag. Smilene deres er smittsomme!",
    "Lyttet til favorittmusikken min og lot tankene fly av sted. #avslapning",
    "Ser frem til helgen for litt velvære og selvpleie. #selfcare",
    "Fant en skjult perle av en kafé i nabolaget mitt. #lokalt",
    "Inspirert av naturens skjønnhet på en morgentur i skogen. #natur",
    "Føler meg takknemlig for de små øyeblikkene som gjør livet verdt å leve.",
    "Satt og reflekterte over livet. Det er så mye å være takknemlig for!",
    "Skrivende ned mål og drømmer for fremtiden. Veien fremover er spennende!",
];
